'use client'

import React, { useState, useMemo } from 'react'
import { Copy, Check, Plus, Trash2 } from 'lucide-react'

type RuleType = 'redirect-301' | 'redirect-302' | 'force-https' | 'force-www' | 'remove-www' | 'deny-directory' | 'block-ip' | 'error-page'

interface Rule {
  id: number
  type: RuleType
  from?: string
  to?: string
  ip?: string
  code?: string
  page?: string
}

const RULE_LABELS: Record<RuleType, string> = {
  'redirect-301': '301 Permanent Redirect',
  'redirect-302': '302 Temporary Redirect',
  'force-https': 'Force HTTPS',
  'force-www': 'Force WWW',
  'remove-www': 'Remove WWW',
  'deny-directory': 'Deny Directory Browsing',
  'block-ip': 'Block IP Address',
  'error-page': 'Custom Error Page',
}

function generateRule(rule: Rule): string {
  switch (rule.type) {
    case 'redirect-301':
      return `# 301 Permanent Redirect\nRedirect 301 ${rule.from || '/old-page'} ${rule.to || 'https://example.com/new-page'}`
    case 'redirect-302':
      return `# 302 Temporary Redirect\nRedirect 302 ${rule.from || '/temp-page'} ${rule.to || 'https://example.com/new-page'}`
    case 'force-https':
      return `# Force HTTPS\nRewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`
    case 'force-www':
      return `# Force WWW\nRewriteEngine On\nRewriteCond %{HTTP_HOST} !^www\\. [NC]\nRewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]`
    case 'remove-www':
      return `# Remove WWW\nRewriteEngine On\nRewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]\nRewriteRule ^(.*)$ https://%1/$1 [R=301,L]`
    case 'deny-directory':
      return `# Deny Directory Browsing\nOptions -Indexes`
    case 'block-ip':
      return `# Block IP Address\n<Limit GET POST PUT>\n  Order allow,deny\n  Allow from all\n  Deny from ${rule.ip || '192.168.1.1'}\n</Limit>`
    case 'error-page':
      return `# Custom Error Page\nErrorDocument ${rule.code || '404'} ${rule.page || '/404.html'}`
    default:
      return ''
  }
}

const PRESETS: { label: string; rules: Omit<Rule, 'id'>[] }[] = [
  {
    label: 'WordPress Hardened',
    rules: [
      { type: 'force-https' },
      { type: 'remove-www' },
      { type: 'deny-directory' },
      { type: 'error-page', code: '404', page: '/404.html' },
    ],
  },
  {
    label: 'Site Migration',
    rules: [
      { type: 'force-https' },
      { type: 'redirect-301', from: '/old-blog', to: 'https://example.com/blog' },
      { type: 'remove-www' },
    ],
  },
]

export default function HtaccessGenerator() {
  const [rules, setRules] = useState<Rule[]>([
    { id: 1, type: 'force-https' },
    { id: 2, type: 'remove-www' },
  ])
  const [copied, setCopied] = useState(false)

  const addRule = (type: RuleType) => {
    setRules(prev => [...prev, { id: Date.now(), type }])
  }

  const removeRule = (id: number) => {
    setRules(prev => prev.filter(r => r.id !== id))
  }

  const updateRule = (id: number, updates: Partial<Rule>) => {
    setRules(prev => prev.map(r => r.id === id ? { ...r, ...updates } : r))
  }

  const applyPreset = (preset: typeof PRESETS[0]) => {
    setRules(preset.rules.map((r, i) => ({ ...r, id: Date.now() + i })))
  }

  const output = useMemo(() => {
    const lines = ['# Generated by WebToolkit Pro .htaccess Generator', '# https://wtkpro.site/tools/htaccess-generator/', '']
    if (rules.some(r => r.type.includes('redirect') || r.type === 'force-https' || r.type === 'force-www' || r.type === 'remove-www')) {
      lines.push('RewriteEngine On', '')
    }
    rules.forEach(rule => {
      lines.push(generateRule(rule))
      lines.push('')
    })
    return lines.join('\n')
  }, [rules])

  const copy = () => {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const ruleTypes = Object.keys(RULE_LABELS) as RuleType[]

  return (
    <div className="space-y-8">
      {/* Presets */}
      <div className="space-y-3">
        <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Quick Presets</label>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((p, i) => (
            <button key={i} onClick={() => applyPreset(p)} className="px-4 py-2 bg-[#0D1526] border border-[#1E2D47] text-gray-300 rounded-xl text-xs font-bold hover:border-[#00D4B4]/50 hover:text-[#00D4B4] transition-all">
              {p.label}
            </button>
          ))}
        </div>
      </div>

      {/* Add Rules */}
      <div className="space-y-3">
        <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Add Rules</label>
        <div className="flex flex-wrap gap-2">
          {ruleTypes.map(type => (
            <button key={type} onClick={() => addRule(type)} className="flex items-center gap-1.5 px-3 py-2 bg-[#0D1526] border border-[#1E2D47] text-gray-400 rounded-xl text-[10px] font-bold hover:border-[#00D4B4]/40 hover:text-[#00D4B4] transition-all">
              <Plus className="w-3 h-3" /> {RULE_LABELS[type]}
            </button>
          ))}
        </div>
      </div>

      {/* Rules List */}
      <div className="space-y-3">
        {rules.map(rule => (
          <div key={rule.id} className="p-4 bg-[#0D1526] border border-[#1E2D47] rounded-2xl space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-[#00D4B4]">{RULE_LABELS[rule.type]}</span>
              <button onClick={() => removeRule(rule.id)} className="text-red-500 hover:text-red-400 transition-colors">
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
            {(rule.type === 'redirect-301' || rule.type === 'redirect-302') && (
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-[9px] font-bold text-gray-500 uppercase tracking-wider">From Path</label>
                  <input value={rule.from || ''} onChange={e => updateRule(rule.id, { from: e.target.value })} placeholder="/old-url" className="w-full mt-1 px-3 py-2 bg-[#0B1120] border border-[#1E2D47] rounded-lg text-xs font-mono text-white focus:ring-1 focus:ring-[#00D4B4] outline-none" />
                </div>
                <div>
                  <label className="text-[9px] font-bold text-gray-500 uppercase tracking-wider">To URL</label>
                  <input value={rule.to || ''} onChange={e => updateRule(rule.id, { to: e.target.value })} placeholder="https://example.com/new-url" className="w-full mt-1 px-3 py-2 bg-[#0B1120] border border-[#1E2D47] rounded-lg text-xs font-mono text-white focus:ring-1 focus:ring-[#00D4B4] outline-none" />
                </div>
              </div>
            )}
            {rule.type === 'block-ip' && (
              <div>
                <label className="text-[9px] font-bold text-gray-500 uppercase tracking-wider">IP Address to Block</label>
                <input value={rule.ip || ''} onChange={e => updateRule(rule.id, { ip: e.target.value })} placeholder="192.168.1.1" className="w-full mt-1 px-3 py-2 bg-[#0B1120] border border-[#1E2D47] rounded-lg text-xs font-mono text-white focus:ring-1 focus:ring-[#00D4B4] outline-none" />
              </div>
            )}
            {rule.type === 'error-page' && (
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-[9px] font-bold text-gray-500 uppercase tracking-wider">Error Code</label>
                  <select value={rule.code || '404'} onChange={e => updateRule(rule.id, { code: e.target.value })} className="w-full mt-1 px-3 py-2 bg-[#0B1120] border border-[#1E2D47] rounded-lg text-xs text-white focus:ring-1 focus:ring-[#00D4B4] outline-none">
                    {['400', '401', '403', '404', '500', '502', '503'].map(c => <option key={c}>{c}</option>)}
                  </select>
                </div>
                <div>
                  <label className="text-[9px] font-bold text-gray-500 uppercase tracking-wider">Error Page Path</label>
                  <input value={rule.page || ''} onChange={e => updateRule(rule.id, { page: e.target.value })} placeholder="/404.html" className="w-full mt-1 px-3 py-2 bg-[#0B1120] border border-[#1E2D47] rounded-lg text-xs font-mono text-white focus:ring-1 focus:ring-[#00D4B4] outline-none" />
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Output */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <label className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">.htaccess Output</label>
          <button onClick={copy} className="flex items-center gap-1.5 px-4 py-2 bg-[#00D4B4]/10 border border-[#00D4B4]/30 text-[#00D4B4] rounded-xl text-xs font-bold hover:bg-[#00D4B4]/20 transition-all">
            {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy .htaccess'}
          </button>
        </div>
        <pre className="w-full bg-[#0B1120] border border-[#1E2D47] rounded-2xl p-6 font-mono text-xs text-[#8A9BBE] whitespace-pre-wrap overflow-auto max-h-[400px]">
          {output}
        </pre>
      </div>
    </div>
  )
}
